// pages/api/robots.txt.ts
import type { NextApiRequest, NextApiResponse } from "next";

export default function handler(req: NextApiRequest, res: NextApiResponse) {
  const host = req.headers.host;
  const inProd =
    process.env.NODE_ENV === "production" && host === "kristiansenutvikling.no";

  const lines = [
    "# Automatically generated by Next.js",
    "User-agent: *",
    inProd ? "Allow: /" : "Disallow: /", // only allow crawling in prod
    "Crawl-delay: 10", // polite pause (seconds)
    "",
    "# Block internal Next.js files & private routes",
    "Disallow: /_next/", // JS/CSS chunk files
    "Disallow: /api/private/", // your private API namespace
    "Disallow: /admin/", // any admin panel
    "",
    `Sitemap: https://${host}/sitemap.xml`,
  ];

  // Cache for 1 hour in prod, no cache otherwise
  if (inProd) {
    res.setHeader(
      "Cache-Control",
      "public, max-age=3600, stale-while-revalidate=86400"
    );
  } else {
    res.setHeader("Cache-Control", "no-store");
  }

  res.setHeader("Content-Type", "text/plain; charset=utf-8");
  res.write(lines.join("\n"));
  res.end();
}
