// src/app/robots.txt/route.ts

export async function GET(request: Request) {
  const host = request.headers.get("host") || "";
  const inProd =
    process.env.NODE_ENV === "production" && host === "kristiansenutvikling.no";

  const lines = [
    "# Automatically generated by Next.js",
    "User-agent: *",
    inProd ? "Allow: /" : "Disallow: /",
    "Crawl-delay: 10",
    "",
    "# Block internal Next.js files & private routes",
    "Disallow: /_next/",
    "Disallow: /api/private/",
    "Disallow: /admin/",
    "",
    `Sitemap: https://${host}/sitemap.xml`,
    `Sitemap: https://${host}/artikler`,
  ];

  return new Response(lines.join("\n"), {
    status: 200,
    headers: {
      "Content-Type": "text/plain; charset=utf-8",
      ...(inProd
        ? {
            "Cache-Control":
              "public, max-age=3600, stale-while-revalidate=86400",
          }
        : { "Cache-Control": "no-store" }),
    },
  });
}
